version: "3.8"

services:

  ubicoders_yt_module3:
    container_name: mavlink_test_cnt
    # build: .
    image: ubicoders/ros2:humble_px4
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: ["/bin/bash"]
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1 
    volumes:
      - "./src:/home/ubuntu/mavlink_test"
      - "/tmp/.X11-unix/:/tmp/.X11-unix/:rw"
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
      - "/dev/:/dev/"